title: Jekyll theme Samen Onder Handbereik

description: >-
   Jekyll theme Samen Onder Handbereik

plugins:
  - jekyll-algolia
  - jekyll-remote-theme

markdown: kramdown

plugins:
  - jekyll-redirect-from

collections:
  pages:
    output: true
  content:
    output: true
    permalink: /:path

defaults:
  - scope:
      path: ''
      type: pages
    values:
      layout: default
  - scope:
      path: ''
      type: content
    values:
      layout: default

sass:
  load_paths:
    - _sass

github: Ewout124/jekyll-theme-soh
